import { IndianState, BusinessSettings, InvoiceTemplateId } from '../types';

export const INDIAN_STATES: IndianState[] = [
  { code: '01', name: 'Jammu & Kashmir' },
  { code: '02', name: 'Himachal Pradesh' },
  { code: '03', name: 'Punjab' },
  { code: '04', name: 'Chandigarh' },
  { code: '05', name: 'Uttarakhand' },
  { code: '06', name: 'Haryana' },
  { code: '07', name: 'Delhi' },
  { code: '08', name: 'Rajasthan' },
  { code: '09', name: 'Uttar Pradesh' },
  { code: '10', name: 'Bihar' },
  { code: '11', name: 'Sikkim' },
  { code: '12', name: 'Arunachal Pradesh' },
  { code: '13', name: 'Nagaland' },
  { code: '14', name: 'Manipur' },
  { code: '15', name: 'Mizoram' },
  { code: '16', name: 'Tripura' },
  { code: '17', name: 'Meghalaya' },
  { code: '18', name: 'Assam' },
  { code: '19', name: 'West Bengal' },
  { code: '20', name: 'Jharkhand' },
  { code: '21', name: 'Odisha' },
  { code: '22', name: 'Chhattisgarh' },
  { code: '23', name: 'Madhya Pradesh' },
  { code: '24', name: 'Gujarat' },
  { code: '27', name: 'Maharashtra' },
  { code: '29', name: 'Karnataka' },
  { code: '30', name: 'Goa' },
  { code: '32', name: 'Kerala' },
  { code: '33', name: 'Tamil Nadu' },
  { code: '36', name: 'Telangana' },
  { code: '37', name: 'Andhra Pradesh' },
];

export interface InvoiceThemeOption {
  id: InvoiceTemplateId;
  name: string;
  category: 'Popular' | 'GST Standard' | 'Landscape' | 'Designer' | 'Classic';
  description: string;
  accent: string;
}

export const INVOICE_THEMES: InvoiceThemeOption[] = [
  { id: 'TALLY', name: 'Tally Theme', category: 'Popular', description: 'Boxed accounting ledger format with authentic Tally borders and font', accent: '#15803d' },
  { id: 'LANDSCAPE_1', name: 'Landscape Theme 1', category: 'Landscape', description: 'Wide horizontal modern layout with side-by-side totals and signatures', accent: '#0369a1' },
  { id: 'LANDSCAPE_2', name: 'Landscape Theme 2', category: 'Landscape', description: 'Wide classic GST layout for wholesale distribution and bulk bills', accent: '#4338ca' },
  { id: 'GST_1', name: 'GST Theme 1', category: 'GST Standard', description: 'Official Government GST Rule 46 format with full CGST/SGST/IGST breakdown', accent: '#000000' },
  { id: 'GST_2', name: 'GST Theme 2', category: 'GST Standard', description: 'Modern Blue Header GST layout with prominent invoice and party badges', accent: '#1d4ed8' },
  { id: 'GST_3', name: 'GST Theme 3', category: 'GST Standard', description: 'Compact Clean GST layout maximizing printable space on single page', accent: '#0f766e' },
  { id: 'GST_4', name: 'GST Theme 4', category: 'GST Standard', description: 'Dual-tone Elegant GST layout with stylized borders and summary tables', accent: '#701a75' },
  { id: 'GST_5', name: 'GST Theme 5', category: 'GST Standard', description: 'Minimalist Monochrome GST layout with sharp lines and high ink-efficiency', accent: '#374151' },
  { id: 'GST_6', name: 'GST Theme 6', category: 'GST Standard', description: 'Enterprise Boxed GST layout with extensive HSN/SAC and itemized tax summary', accent: '#b45309' },
  { id: 'DOUBLE_DIVINE', name: 'Double Divine', category: 'Designer', description: 'Sophisticated luxury invoice with double outline frame and refined styling', accent: '#6d28d9' },
  { id: 'FRENCH_ELITE', name: 'French Elite', category: 'Designer', description: 'Minimalist luxury editorial aesthetic with classic serif typography', accent: '#991b1b' },
  { id: 'THEME_1', name: 'Theme 1', category: 'Classic', description: 'Standard corporate invoice layout with crisp borders', accent: '#1e293b' },
  { id: 'THEME_2', name: 'Theme 2', category: 'Classic', description: 'Modern Vibrant layout with bold colored table headers', accent: '#0284c7' },
  { id: 'THEME_3', name: 'Theme 3', category: 'Classic', description: 'Clean Borderless layout with subtle hairline dividers', accent: '#52525b' },
  { id: 'THEME_4', name: 'Theme 4', category: 'Classic', description: 'Ultra-dense pro format tailored for fast POS desk printing', accent: '#18181b' },
];

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  firmName: '',
  tagline: '',
  gstin: '',
  pan: '',
  phone: '',
  email: '',
  address: '',
  city: '',
  state: '',
  stateCode: '',
  pincode: '',
  bankName: '',
  accountNumber: '',
  ifscCode: '',
  branchName: '',
  upiId: '',
  invoicePrefix: 'INV-',
  nextInvoiceNumber: 1,
  termsAndConditions: '1. Goods once sold will not be taken back.\n2. All disputes are subject to local jurisdiction.',
  defaultInvoiceFormat: 'A4_STANDARD',
  logoUrl: '',
  invoiceCustomization: {
    template: 'GST_1',
    themeColor: '#000000',
    headerTitle: 'TAX INVOICE',
    headerSubtitle: 'Issued under Rule 46 of CGST Rules, 2017',
    logoUrl: '',
    logoWidth: 90,
    logoAlignment: 'left',
    showLogo: true,
    showHsn: true,
    showUnit: true,
    showDiscount: true,
    showTaxBreakdown: true,
    showQrCode: true,
    showBankDetails: true,
    showTerms: true,
    showSignature: true,
    showVehicleDetails: true,
    showTotalInWords: true,
    footerNote: 'Thank you for your business! Visit again.',
    termsAndConditions: '1. Goods once sold will not be taken back.\n2. All disputes are subject to local jurisdiction.',
    printCompanyInfo: true,
    makeRegularPrinterDefault: true,
    printRepeatHeader: true,
    paperSize: 'A4',
    orientation: 'PORTRAIT',
    companyNameTextSize: 5,
    invoiceTextSize: 3,
    extraSpaceOnTopOfPdf: 1,
    printOriginalDuplicate: true,
    defaultCopies: 1,
    originalTitle: 'ORIGINAL FOR RECIPIENT',
    duplicateTitle: 'DUPLICATE FOR TRANSPORTER',
    triplicateTitle: 'TRIPLICATE FOR SUPPLIER',
    expandTableToWholePage: true,
    minItemRows: 0,
    showTotalItemQty: true,
    showAmountWithDecimal: true,
    showReceivedAmount: true,
    showBalanceAmount: true,
    showCurrentBalanceParty: true,
    showTaxDetails: true,
    showYouSaved: true,
    printAmountWithGrouping: true,
    amountInWords: true,
    printDescription: true,
    printTerms: true,
    printReceivedBy: true,
    printDeliveredBy: true,
    signatureText: 'Authorized Signatory',
    printPaymentMode: true,
    printAcknowledgement: true,
  },
  hardwareSettings: {
    enableCameraScanner: true,
    enableHardwareBeep: true,
    autoPrintOnSave: false,
  },
  generalSettings: {
    enablePasscode: false,
    businessCurrency: '₹',
    amountDecimalPlaces: 2,
    showGstinNumber: true,
    stopSaleOnNegativeStock: false,
    blockNewItemsFromTxn: false,
    blockNewPartiesFromTxn: false,
    moreTransactions: {
      estimate: true,
      proforma: true,
      saleOrder: true,
      otherIncome: false,
      fixedAssets: false,
      deliveryChallan: true,
      goodsReturnChallan: true,
      printAmountChallan: false,
    },
    multiFirm: {
      activeFirmId: 'firm-1',
      firms: [
        { id: 'firm-1', name: 'Primary Firm', isDefault: true },
      ],
    },
    godownManagement: true,
    autoBackup: false,
    auditTrail: true,
    screenZoom: 100,
  },
  transactionSettings: {
    header: {
      invoiceNumber: true,
      addTime: false,
      cashSaleByDefault: false,
      billingNameOfParties: false,
      customerPoDetails: false,
    },
    itemsTable: {
      taxRateOnPriceUnit: true,
      displayPurchasePrice: true,
      showLast5SalePrice: false,
      showLast5PurchasePrice: false,
      freeItemQty: false,
      count: false,
    },
    taxesDiscountTotals: {
      transactionWiseTax: false,
      transactionWiseDiscount: true,
      roundOffTotal: true,
      roundOffNearestTo: 1,
    },
    moreFeatures: {
      ewayBillNo: false,
      quickEntry: true,
      doNotShowInvoicePreview: false,
      repeatInvoices: false,
      enablePasscodeForEditDelete: false,
      discountDuringPayments: true,
      linkPaymentsToInvoices: true,
      dueDatesPaymentTerms: true,
      showProfitWhileSale: true,
    },
    prefixes: {
      firm: '',
      sale: 'TaxInvoice',
      creditNote: 'None',
      saleOrder: 'None',
      purchaseOrder: 'None',
      estimate: 'None',
      proformaInvoice: 'None',
      deliveryChallan: 'None',
      paymentIn: 'None',
    },
    billingType: 'FULL',
  },
  partySettings: {
    partyGrouping: true,
    shippingAddress: true,
    printShippingAddress: true,
    managePartyStatus: true,
    enablePaymentReminder: true,
    reminderDueDays: 1,
    reminderMessage: 'Dear {party_name}, your payment of ₹{amount} is due on {due_date}. Please pay at your earliest convenience.',
    additionalFields: [
      { id: 'f1', name: 'Additional Field 1', type: 'text', showInPrint: false },
      { id: 'f2', name: 'Additional Field 2', type: 'text', showInPrint: false },
      { id: 'f3', name: 'Additional Field 3', type: 'text', showInPrint: false },
      { id: 'f4', name: 'Additional Field 4', type: 'date', showInPrint: false },
    ],
    enableLoyaltyPoint: true,
  },
  itemSettings: {
    enableItem: true,
    whatDoYouSell: 'PRODUCT',
    barcodeScan: true,
    directBarcodeScan: false,
    stockMaintenance: true,
    manufacturing: true,
    showLowStockDialog: false,
    itemsUnit: true,
    defaultUnit: 'Pcs',
    itemCategory: true,
    partyWiseItemRate: true,
    description: false,
    itemWiseTax: true,
    itemWiseDiscount: true,
    updateSalePriceFromTxn: false,
    qtyDecimalPlaces: 2,
    mrpPrice: {
      mrp: true,
      calcSalePriceFromMrpDisc: true,
      useMrpForBatchTracking: false,
      calcTaxBasedOnMrp: false,
    },
    serialNoTracking: false,
    batchTracking: {
      batchNo: false,
      expDate: false,
      mfgDate: false,
      modelNo: false,
      size: true,
    },
  },
  taxesGstSettings: {
    gstRegistered: true,
    compositionScheme: false,
    rcmEnabled: false,
    defaultTaxRate: 18,
    enableCess: false,
    ewayBillThreshold: 50000,
    einvoiceThreshold: 50000000,
  },
  transactionMessages: {
    invoiceWhatsApp: 'Dear {party_name}, please find attached your Tax Invoice #{invoice_no} for ₹{amount}. Thank you for your business!',
    paymentReminder: 'Dear {party_name}, this is a gentle reminder that an amount of ₹{amount} is outstanding on invoice #{invoice_no}. Kindly settle at your earliest convenience.',
    challanMessage: 'Dear {party_name}, your delivery challan #{challan_no} has been dispatched. Please verify upon receipt.',
    greetings: 'Thank you for your business! We look forward to serving you again.',
    autoSendWhatsApp: false,
  },
  serviceReminders: {
    enableServiceReminders: true,
    notifyDaysBefore: 3,
    autoSendWhatsApp: true,
    reminderMessage: 'Dear {party_name}, your scheduled service for {item_name} is due on {due_date}. Please contact us to confirm your appointment.',
    autoRenewOnInvoice: true,
  },
  accountingSettings: {
    bookkeepingType: 'DOUBLE_ENTRY',
    financialYearStart: '2024-04-01',
    autoCreateJournalEntries: true,
    roundOffLedgerAccount: 'Round Off Expense / Income A/c',
    warnNegativeCashBalance: true,
    cashInHandAlertLimit: 200000,
  },
  multiCurrencySettings: {
    enableMultiCurrency: false,
    baseCurrency: 'INR',
    baseSymbol: '₹',
    secondaryCurrencies: [
      { code: 'USD', name: 'US Dollar', symbol: '$', exchangeRate: 86.5, active: true },
      { code: 'EUR', name: 'Euro', symbol: '€', exchangeRate: 94.2, active: true },
      { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', exchangeRate: 23.55, active: true },
      { code: 'GBP', name: 'British Pound', symbol: '£', exchangeRate: 110.8, active: false },
    ],
    printDualCurrency: false,
  },
};

export const COMMON_UNITS = [
  'Pcs', 'Box', 'Kg', 'Gm', 'Mtr', 'Roll', 'Set', 'Pack', 'Ltr', 'Dozen', 'Nos'
];

export const GST_RATES: (0 | 5 | 12 | 18 | 28)[] = [0, 5, 12, 18, 28];
